### ISSUE TITLE
Unexpected Scroll Behaviour Github

### ISSUE THREAD

**Issue by nbelzer** [nbelzer/vimari#1]
**Describe the bug**
On pages like GitHub some keys are bound to certain scrolling events such as `k` on any repo page. This conflicts with the scrolling behaviour provided by Vimari and results in unexpected behaviour.

**To Reproduce**
1. Go to any GitHub repo page, take [this](https://github.com/nbelzer/vimari) one for example.
2. Scroll down past the files section.
3. Use `k` to scroll up (this key is both linked to GitHub and Vimari).
4. You will see an instant jump back to the files section (as per Github) instead of a small scroll of your predefined `scrollSize` (as per Vimari).

**Expected behaviour**
The page to scroll up with the defined `scrollSize`.

 - macOS version: Unrelated
 - Safari version: Unrelated
 - Vimari version: `2.0.3`

**Comment by nbelzer** [comment]
There are likely more cases where overlapping functionality is bound to both the website visited and Vimari. This provides a few options:
- **Eliminate the behaviour of the website visited**
  Likely not a good idea as we do not know what this behaviour is.
- **Try to detect and notify the user**
  This would at least make the behaviour expected to the user.
- **Provide the ability to set custom keys for websites**
  Allowing the user to circumvent the issue themselves, however they would have to remember different keybindings for different pages.
- **(Partially) Disable Vimari on selected websites**
  This would allow the user to use the behavior of the website visited but would disable all (or parts) of Vimari. 
- **Give the choice to the user**
  This continues on 'Try to detect' but then gives the decision to the user on whether we should bind this key to Vimari (and unbind the other behaviour), if possible. It would also require keeping track of the preferences per site.

The last one is likely the best from a user perspective, however I'm not sure how feasible this behaviour would be.

**Comment by nikivdev** [comment]
Shouldn't we disable website intercepting those keystrokes when user is in normal mode?

**Comment by nikivdev** [comment]
That's what sVim did.

**Comment by nikivdev** [comment]
I was actually fine with sVim intercepting all keys that are not taken by extension as that is the point of normal mode. The keys are not taken by extension act as if they were keys in insert mode (do what website setup).

**Comment by nbelzer** [comment]
@nikitavoloboev Thanks for the input. I agree that this should be the way to go. I had a look at sVim as you mentioned and found the behaviour to be dictated by these lines in `sVim/sVimTab.js`:

```js
// Stop keydown propagation
document.addEventListener("keydown", sVimTab.stopPropagation(), true);
...
// Prevent propagation for all keydown events if in normal mode, non-escape key is pressed or active element is input
sVimTab.stopPropagation = function() {
  return function(e) {
    var element = document.activeElement;
    var excludeKeys = [27, 38, 40, 37, 39]
    if (sVimTab.mode == "normal" && !excludeKeys.includes(e.keyCode) && (element != null && !sVimHelper.isElementInput(element))) {
      e.stopPropagation();
    }
  };
};
```

Ill try to implement a similar behaviour in this fork of Vimari to stop this unexpected scroll behaviour.

**Comment by nbelzer** [comment]
The behaviour of `sVim` described in my previous comment works as it uses the `useCapture` flag:
> A Boolean indicating whether events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree... ~ [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#The_event_listener_callback)

This means that our `stopPropagation` event handler acts before the event is dispatched to the handlers in the DOM tree. This will however also block out the library used to handle the keys that trigger Vimari actions: mousetrap. Mousetrap however does not [yet](https://github.com/ccampbell/mousetrap/pull/400) offer a setting to enable this flag. Therefore we need to alter the mousetrap library to use the `useCapture` flag for the events that it registers.

This is how `sVim` was able to control when (insert vs normal mode) events propagated to the actual website. I've implemented a similar behaviour in the branch `1-unexpected-scroll-behaviour`.
